/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROPOSTA_H_RPCGEN
#define _PROPOSTA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Stringa {
	char l[50];
};
typedef struct Stringa Stringa;

struct Risultato {
	int caratteri;
	int parole;
	int linee;
};
typedef struct Risultato Risultato;

struct Scansione {
	int numeroFile;
	Stringa files[8];
};
typedef struct Scansione Scansione;

struct Dir {
	Stringa dir;
	int soglia;
};
typedef struct Dir Dir;

#define PROPOSTAPROG 0x200000AA
#define PROPOSTAVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define FILE_SCAN 1
extern  Risultato * file_scan_1(Stringa *, CLIENT *);
extern  Risultato * file_scan_1_svc(Stringa *, struct svc_req *);
#define DIR_SCAN 2
extern  Scansione * dir_scan_1(Dir *, CLIENT *);
extern  Scansione * dir_scan_1_svc(Dir *, struct svc_req *);
extern int propostaprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FILE_SCAN 1
extern  Risultato * file_scan_1();
extern  Risultato * file_scan_1_svc();
#define DIR_SCAN 2
extern  Scansione * dir_scan_1();
extern  Scansione * dir_scan_1_svc();
extern int propostaprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Stringa (XDR *, Stringa*);
extern  bool_t xdr_Risultato (XDR *, Risultato*);
extern  bool_t xdr_Scansione (XDR *, Scansione*);
extern  bool_t xdr_Dir (XDR *, Dir*);

#else /* K&R C */
extern bool_t xdr_Stringa ();
extern bool_t xdr_Risultato ();
extern bool_t xdr_Scansione ();
extern bool_t xdr_Dir ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROPOSTA_H_RPCGEN */
