/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "proposta.h"

Risultato *
file_scan_1_svc(Stringa *argp, struct svc_req *rqstp)
{
	static Risultato  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Scansione *
dir_scan_1_svc(Dir *argp, struct svc_req *rqstp)
{
	static Scansione  result;

	/*
	 * insert server code here
	 */

	return &result;
}
