/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "proposta.h"

void
propostaFileScan_1(char *host, Stringa* file)
{
	CLIENT *clnt;
	Risultato  *result_1;

#ifndef	DEBUG
	clnt = clnt_create (host, PROPOSTAPROG, PROPOSTAVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = file_scan_1(file, clnt);
	if (result_1 == (Risultato *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
	printf("Caratteri %d, Parole %d, Linee %d\n", (*result_1).caratteri,(*result_1).parole,(*result_1).linee);}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

void
propostaDirScan_1(char *host,Dir *direttorio)
{
	CLIENT *clnt;
	Scansione  *result_2;

#ifndef	DEBUG
	clnt = clnt_create (host, PROPOSTAPROG, PROPOSTAVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	result_2 = dir_scan_1(direttorio, clnt);
	if (result_2 == (Scansione *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		if(result_2->numeroFile<0){
			printf("La cartella indicata non esiste oppure non può esser aperta");
		}
	for(int i=0;i<(*result_2).numeroFile;i++){
		printf("%s\n",(*result_2).files[i].l);
	}}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}



int
main (int argc, char *argv[])
{
	char *host;
	char *file;
	Dir direttorio;
	Stringa fileprova;
	int soglia;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	if(argc==3){
		strcpy(fileprova.l, argv[2]);
		propostaFileScan_1(host,&fileprova);
	}
	if(argc==4){
		strcpy(direttorio.dir.l , argv[2]);
		direttorio.soglia=atoi(argv[3]);
		propostaDirScan_1(host,&direttorio);
	}
	exit (0);
}





