/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "proposta.h"

bool_t
xdr_Stringa (XDR *xdrs, Stringa *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->l, 50,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Risultato (XDR *xdrs, Risultato *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->caratteri))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->parole))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->linee))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Scansione (XDR *xdrs, Scansione *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->numeroFile))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->files, 8,
		sizeof (Stringa), (xdrproc_t) xdr_Stringa))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Dir (XDR *xdrs, Dir *objp)
{
	register int32_t *buf;

	 if (!xdr_Stringa (xdrs, &objp->dir))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->soglia))
		 return FALSE;
	return TRUE;
}
